### ISSUE TITLE
Add a complete example file 

### ISSUE THREAD

**Issue by lalo4ka** [shahnawaz/react-native-barcode-mask#34]
Hi, thank you for this plugin :) 
i would like to recommend you something.

Add a complete file example in you documentation. 

Actually you already have one: https://gist.github.com/shahnawaz/d24ae843fc3a6056bef9c752d9b35e03

**Comment by shahnawaz** [comment]
:tada: This issue is resolved in version 1.2.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-barcode-mask/v/1.2.3)
- [GitHub release](https://github.com/shahnawaz/react-native-barcode-mask/releases/tag/v1.2.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
